# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself

default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean" 
    sh "flutter build apk --release --flavor production -t lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
  app: "1:134724234264:android:0308f00e107d2eada9276d",
  firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
  android_artifact_type: "APK",
  android_artifact_path:"build/app/outputs/flutter-apk/app-production-release.apk",
  testers: "engmuna2002m@gmail.com",
  release_notes: "First Fastlane Firebase App Distribution"
)

  end
end
